--
-- Create table statements 
--
-- Generated by datagenerator. www.dominicgiles.com
--

DROP TABLE ANPR_RELATIONAL PURGE;
DROP TABLE anpr_collection PURGE;
DROP TABLE SIMPLETABLE PURGE;

CREATE TABLE ANPR_RELATIONAL (
  anpr_id            NUMBER(10) NOT NULL,
  collection_time    DATE       NOT NULL,
  location_id        NUMBER(10) NOT NULL,
  number_plate       VARCHAR2(10),
  oracar_pass_id     VARCHAR2(20),
  payment            NUMBER(6),
  vehicle_colour     VARCHAR2(30),
  vehicle_type       VARCHAR2(30),
  watch_list         CHAR(1),
  number_plate_image CLOB
)
INITRANS 128
STORAGE (INITIAL 1G NEXT 1G
)
LOB (number_plate_image) STORE AS SECUREFILE (
CACHE READS
NOLOGGING
);

CREATE TABLE anpr_collection (
  anprid          NUMBER(10) NOT NULL,
  collection_time DATE       NOT NULL,
  json_data       CLOB       NOT NULL,
  CONSTRAINT json_constraint CHECK (json_data IS JSON (LAX))
)
INITRANS 128
STORAGE (INITIAL 1G NEXT 1G)
LOB (json_data) STORE AS SECUREFILE (
CACHE READS
NOLOGGING
);

CREATE TABLE SIMPLETABLE (
COLUMN1		NUMBER(12)	NOT NULL,
COLUMN2		NUMBER(6) NOT NULL,
COLUMN3		NUMBER(6)	NOT NULL,
COLUMN4		NUMBER(6)	NOT NULL,
COLUMN5		NUMBER(6)	NOT NULL,
COLUMN6		DATE	NOT NULL
)
INITRANS 128
STORAGE (INITIAL 1G NEXT 1G);


DROP INDEX anpr_r_idx;

CREATE INDEX anpr_r_idx
  ON ANPR_RELATIONAL (ANPR_ID, COLLECTION_TIME);

DROP INDEX anpr_d_idx;

CREATE INDEX anpr_d_idx
  ON anpr_collection (anprid, collection_time);